/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A parsed HTML document.
 *
 * @example
 * ```javascript
 * import { Soup } from 'scrape-rs';
 *
 * const soup = new Soup("<div>Hello</div>");
 * const div = soup.find("div");
 * console.log(div.text); // "Hello"
 * ```
 */
export declare class Soup {
  /**
   * Parse an HTML string into a Soup document.
   *
   * @param html - HTML string to parse
   * @param config - Optional parsing configuration
   */
  constructor(html: string, config?: SoupConfig | undefined | null)
  /**
   * Parse HTML from a file.
   *
   * @param path - Path to the HTML file
   * @param config - Optional parsing configuration
   * @returns A new Soup instance
   * @throws Error if the file cannot be read
   */
  static fromFile(path: string, config?: SoupConfig | undefined | null): Soup
  /**
   * Find the first element matching a CSS selector.
   *
   * @param selector - CSS selector string
   * @returns The first matching Tag, or null if not found
   * @throws Error if the selector syntax is invalid
   */
  find(selector: string): Tag | null
  /**
   * Find all elements matching a CSS selector.
   *
   * @param selector - CSS selector string
   * @returns Array of matching Tag instances
   * @throws Error if the selector syntax is invalid
   */
  findAll(selector: string): Array<Tag>
  /**
   * Find all elements matching a CSS selector (alias for findAll).
   *
   * @param selector - CSS selector string
   * @returns Array of matching Tag instances
   */
  select(selector: string): Array<Tag>
  /**
   * Get the root element of the document.
   *
   * @returns The root Tag (usually <html>), or null for empty documents
   */
  get root(): Tag | null
  /**
   * Get the document title.
   *
   * @returns The title text, or null if no <title> element exists
   */
  get title(): string | null
  /**
   * Get the text content of the entire document.
   *
   * @returns All text content with HTML tags stripped
   */
  get text(): string
  /**
   * Get the HTML representation of the document.
   *
   * @returns The document as an HTML string
   */
  toHtml(): string
  /** Get the number of nodes in the document. */
  get length(): number
}

/**
 * An HTML element in the document.
 *
 * Provides access to element content, attributes, and tree navigation.
 *
 * @example
 * ```javascript
 * const soup = new Soup('<div class="test">Hello</div>');
 * const div = soup.find("div");
 * console.log(div.name);         // "div"
 * console.log(div.text);         // "Hello"
 * console.log(div.attr("class")); // "test"
 * ```
 */
export declare class Tag {
  /** Get the tag name (e.g., "div", "span"). */
  get name(): string | null
  /** Get the text content of this element and all descendants. */
  get text(): string
  /** Get the inner HTML content (excluding this element's tags). */
  get innerHTML(): string
  /** Get the outer HTML (including this element's tags). */
  get outerHTML(): string
  /**
   * Get an attribute value by name.
   *
   * @param name - The attribute name
   * @returns The attribute value, or null if not present
   */
  attr(name: string): string | null
  /**
   * Get an attribute value by name (alias for attr).
   *
   * @param name - The attribute name
   * @returns The attribute value, or null if not present
   */
  get(name: string): string | null
  /**
   * Check if the element has an attribute.
   *
   * @param name - The attribute name
   * @returns True if the attribute exists
   */
  hasAttr(name: string): boolean
  /** Get all attributes as an object. */
  get attrs(): Record<string, string>
  /**
   * Check if the element has a specific class.
   *
   * @param className - The class name to check
   * @returns True if the element has the class
   */
  hasClass(className: string): boolean
  /** Get all classes as an array. */
  get classes(): Array<string>
  /** Get the parent element. */
  get parent(): Tag | null
  /** Get all direct child elements. */
  get children(): Array<Tag>
  /** Get the next sibling element. */
  get nextSibling(): Tag | null
  /** Get the previous sibling element. */
  get prevSibling(): Tag | null
  /** Get all descendant elements. */
  get descendants(): Array<Tag>
  /**
   * Find the first descendant matching a CSS selector.
   *
   * @param selector - CSS selector string
   * @returns The first matching Tag, or null if not found
   * @throws Error if the selector syntax is invalid
   */
  find(selector: string): Tag | null
  /**
   * Find all descendants matching a CSS selector.
   *
   * @param selector - CSS selector string
   * @returns Array of matching Tag instances
   * @throws Error if the selector syntax is invalid
   */
  findAll(selector: string): Array<Tag>
  /** Find all descendants matching a CSS selector (alias for findAll). */
  select(selector: string): Array<Tag>
  /** Get the number of direct child elements. */
  get length(): number
}

/**
 * Parse multiple HTML documents in parallel.
 *
 * Uses Rayon for parallel processing. Provides significant speedup
 * when parsing many documents.
 *
 * @param documents - Array of HTML strings to parse
 * @param config - Optional parsing configuration
 * @returns Array of Soup instances in the same order as input
 *
 * @example
 * ```javascript
 * import { parseBatch } from 'scrape-rs';
 *
 * const htmls = ['<div>A</div>', '<div>B</div>', '<div>C</div>'];
 * const soups = parseBatch(htmls);
 * const texts = soups.map(s => s.find('div').text);
 * // texts: ['A', 'B', 'C']
 * ```
 */
export declare function parseBatch(documents: Array<string>, config?: SoupConfig | undefined | null): Array<Soup>

/**
 * Configuration options for HTML parsing.
 *
 * @example
 * ```javascript
 * const config = {
 *   maxDepth: 256,
 *   strictMode: false,
 *   preserveWhitespace: false,
 *   includeComments: false
 * };
 * const soup = new Soup("<div>Hello</div>", config);
 * ```
 */
export interface SoupConfig {
  /** Maximum nesting depth for DOM tree. Default: 512 */
  maxDepth?: number
  /** Enable strict parsing mode. Default: false */
  strictMode?: boolean
  /** Preserve whitespace-only text nodes. Default: false */
  preserveWhitespace?: boolean
  /** Include comment nodes in DOM. Default: false */
  includeComments?: boolean
}

/** Get the library version. */
export declare function version(): string
